version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db

  flask_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    depends_on:
      - mongodb

volumes:
  mongo_data:
